#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
HELP_PLUGIN_COMMAND="help"
HELP_PLUGIN_ALLOW_ALIAS="false"
HELP_PLUGIN_FUNCTION="helpRun"

# Echo help content
function helpRun {

	echo "
Usage: eiger [COMMAND] [ARG...]
	
Run a command that runs in a docker container

Commands:"

  # Loop through each plugin
	for PLUGIN in "${PLUGINS[@]}"
	do
	  # If the plugin variable help variable exist and the value is the name of a function run the function
	  local COMMANDVAR=${PLUGIN}_PLUGIN_HELP_COMMAND
		if [ ! -z $(eval echo "$"$COMMANDVAR) ] && ! typeset -f $(eval echo "$"${PLUGIN}_PLUGIN_HELP_COMMAND) > /dev/null; then
      local COMMAND=$(eval echo "$"${PLUGIN}_PLUGIN_HELP_COMMAND)
      local TEXT=$(eval echo "$"${PLUGIN}_PLUGIN_HELP_TEXT)

      printf "  %-20s$TEXT\n" $COMMAND
		fi
	done | sort -n
}