#!/bin/bash

DEBUG=false
INSTALL_PATH=~/.eiger
USERDATA_PATH=$INSTALL_PATH/userdata

####################################################
# Functions
####################################################

# Echo debug content if debug is enabled
function debug {

	if [ $DEBUG == "true" ]; then
		message "DEBUG" "${1}"
	fi
}

# Echo message with time prefixed
function message {

	TIMESTAMP=`date "+%H:%M:%S"`

	echo "[$TIMESTAMP] ${1} - ${2}"
}

# Check certain commands are installed
function checkCommands {

	debug "Running command checks."

	if ! [ -x "$(command -v git)" ]; then
		message "ERROR" "Git is not installed. Exiting..."
		exit 1
	else
		debug "Confirmed Git is installed."
	fi

	debug "Finished running command checks."
}

# Run local to install
function runInstaller {

    if [ -f "$INSTALL_PATH/.eiger/eiger" ]; then
        message "ERROR" "Eiger is already installed, please use the updater to update. Exiting..."
        exit 1
    fi

    if ! mkdir -p $INSTALL_PATH; then
        message "ERROR" "There was an error making the installation directory ($INSTALL_PATH). Exiting..."
        exit 1
    fi

    cd $INSTALL_PATH;

    if git clone https://github.com/zimosworld/eiger.git .; then

        message "INFO" "Eiger downloaded, now installing, this may require sudo access..."

        case "$(uname -s)" in
            Darwin*|Linux*)
                local mainPath="$(echo "$INSTALL_PATH/bin" 2>&1 | sudo tee -a /etc/paths 2>&1)"
                local mainPath="$(echo "$USERDATA_PATH/composer/vendor/bin" 2>&1 | sudo tee -a /etc/paths 2>&1)"

                if [[ "$mainPath" != "$INSTALL_PATH/bin" ]]; then
                    message "ERROR" "Error updating path. Installation stopped..."
                    exit 1
                fi
                ;;
            CYGWIN*|MINGW*)
                touch ~/.eiger/eiger.aliases

                if echo "
PATH=\$PATH:~/.eiger
source ~/.eiger/eiger.aliases
alias alias_refresh='source ~/.eiger/eiger.aliases'" >> ~/.bashrc; then

                    chmod 740 ~/.eiger/eiger

                    source ~/.bashrc
                    message "INFO" "Alias added successfully, installation completed."
                else
                    message "ERROR" "There was an error adding Alias. Exiting..."
                fi

              ;;
        esac

    else
        message "ERROR" "There was an issue pulling down the script. Exiting..."
    fi
}

runInstaller