#!/bin/bash

if [ "$(uname -s)" = 'Darwin' ]; then
  SCRIPTPATH=$(dirname "$0")
else
  SCRIPT=$(readlink -f "$0")
  SCRIPTPATH=$(dirname "$SCRIPT")
fi

COREPATH=$SCRIPTPATH/core

####################################################
# Functions
####################################################

if [ -f "$COREPATH/core" ]; then
  source $COREPATH/core
else
  echo "ERROR" "Missing core file \"core\" please reinstall eiger to resolve. Exiting..."
	exit 1
fi
