#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
VERSION_VERSION=1.0.0
VERSION_COMMAND="version"
VERSION_FUNCTION="versionRun"
VERSION_HELP="versionHelp"

function versionRun {
	message "INFO" "Eiger version: $VERSION"
}

# Function for output top level help
function versionHelp {
	printf "   version\t\tOutput version of eiger."
}