#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
VERSION_PLUGIN_VERSION=1.1.0
VERSION_PLUGIN_COMMAND="version"
VERSION_PLUGIN_FUNCTION="versionRun"
VERSION_PLUGIN_HELP="versionHelp"

function versionRun {
	message "INFO" "Eiger version: $VERSION"
}

# Function for output top level help
function versionHelp {
	printf "  version\t\tOutput version of eiger."
}