#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
DOCKERENV_PLUGIN_VERSION=1.1.0
DOCKERENV_PLUGIN_COMMAND="dei docker-env-init"
DOCKERENV_PLUGIN_HELP_COMMAND="dei"
DOCKERENV_PLUGIN_HELP_TEXT="Creates .docker.env with settings based on system OS."
DOCKERENV_PLUGIN_FUNCTION="dockerEnvRun"
DOCKERENV_PLUGIN_HELP="dockerEnvHelp"

# Create .docker.env file to work with containers based off https://github.com/zimosworld/php-dev
function dockerEnvRun {

	if [ -f "$(pwd)/.docker.env" ]; then
		message "INFO" ".docker.env file already exists.\nExiting..."
		exit 1
	fi
	
	message "INFO" "Creating .docker.env file with OS as $OS_TYPE"
	echo "HOST_UNAME=$OS_TYPE" > .docker.env
	
	if [ $OS_TYPE = Linux ]; then
		echo "HOST_UID=$USER
HOST_GID=$GROUP" >> .docker.env
	fi
	
	message "INFO" "Creating .docker.env completed"

}