#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
INIT_PLUGIN_COMMAND="init"
INIT_PLUGIN_ALLOW_ALIAS="false"
INIT_PLUGIN_HELP_COMMAND="init"
INIT_PLUGIN_HELP_TEXT="Initialize Eiger on project."
INIT_PLUGIN_FUNCTION="initRun"
INIT_PLUGIN_HELP="initHelp"

# Initialize eiger for project (Creates .eiger file after asking some questions)
function initRun {
	if [ -f "$(pwd)/.eiger" ]; then
		message "INFO" "Eiger is already setup.\nExiting..."
		exit 1
	fi
	
	CONTENT=""

	# Loop through each plguin
	for PLUGIN in "${PLUGINS[@]}"
	do
	  # If the plugin has a init variable and its value is the name of a function
	  FUNCTIONNAME=${PLUGIN}_PLUGIN_INIT
		if [ ! -z $(eval echo "$"$FUNCTIONNAME) ] && typeset -f $(eval echo "$"${PLUGIN}_PLUGIN_INIT) > /dev/null; then
		  # Get plugin command
			COMMAND=$(eval echo "$"${PLUGIN}_PLUGIN_INIT)

			# Run plugin command and capture result
			CONTENT+="$(eval $COMMAND)\n"
		fi
	done

	# Save content to file
	printf "$CONTENT" > .eiger
}