#!/bin/bash

# Echo debug content if debug is enabled
function debug {

	if [ $DEBUG == "true" ]; then
		message "DEBUG" "${1}" 
	fi
}

# Echo message with time prefixed
function message {
	
	TIMESTAMP=`date "+%H:%M:%S"`
	
	printf "[$TIMESTAMP] ${1} - ${2}\n"
	
	if [ $1 = "ERROR" ]; then
		echo "Exiting..."
		exit 1
	fi
}

# Echo info with info tag and message
function echo_info {

  message "INFO" "${1}"
}

# Check certain commands are installed
function checkCommands {

	debug "Running command checks."

	if ! [ -x "$(command -v docker)" ]; then
		message "ERROR" "Docker is not installed."
	else
		debug "Confirmed Docker is installed."
	fi
	
	if ! [ -x "$(command -v git)" ]; then
		message "ERROR" "Git is not installed."
	else
		debug "Confirmed Git is installed."
	fi
	
	debug "Finished running command checks."
}

# Ask Y/N Question and loop until valid response
function ask {

    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        echo -n "$1 [$prompt]:" >&2

        read reply </dev/tty

        if [ -z "$reply" ]; then
            reply=$default
        fi

        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}

# Create global editable config file with default settings
function createConfig {

  if [ -f "$SCRIPTPATH/eiger.config" ]; then
    return
  fi

  debug "Creating eiger.config file."

  local CONFIGCONTENT="DEBUG=false"

  printf "$CONFIGCONTENT" > "$SCRIPTPATH/eiger.config"
}

# Load global config file
function loadConfig {

  if [ -f $SCRIPTPATH/eiger.config ]; then
    source $SCRIPTPATH/eiger.config
  else
    debug "Missing eiger.config file."

    createConfig

    if [ -f $SCRIPTPATH/eiger.config ]; then
      source $SCRIPTPATH/eiger.config
    fi
  fi
}

#$1=Plugin Name
#$2=Variable Name/Template
#$3=Default value (If global and local overwrite does not exist)

# Get setting value checking for local and global version overwrite
function getSettingValue {

  local PLUGINNAME=$1
  local VARIABLETEMPLATE=$2
  local VALUE=$3

  # Global overwrite check for variable
  if [ ! -z $(eval echo "$"${PLUGINNAME}_GLOBAL_${VARIABLETEMPLATE}) ]; then
    VALUE=$(eval echo "$"${PLUGINNAME}_GLOBAL_${VARIABLETEMPLATE})
  fi;

  # Local overwrite check for variable
  if [ ! -z $(eval echo "$"${PLUGINNAME}_${VARIABLETEMPLATE}) ]; then
    VALUE=$(eval echo "$"${PLUGINNAME}_${VARIABLETEMPLATE})
  fi;

  echo $VALUE
}

# Get docker image setting, checking for local and global version overwrite
function getDockerImageSetting {

  echo $(getSettingValue $1 "DOCKER_IMAGE" $(eval echo "$"${1}_PLUGIN_DOCKER_IMAGE))
}

# Get docker image version setting, checking for local and global version overwrite
function getDockerImageVersionSetting {

  echo $(getSettingValue $1 "DOCKER_IMAGE_VERSION" $(eval echo "$"${1}_PLUGIN_DOCKER_IMAGE_VERSION))
}

function getPluginStoragePath {

  local path="${STORAGEPATH}/${1}"

  if [[ ! -z $2 ]]; then
      path+=$2
  fi

  echo $path
}