#!/bin/bash

####################################################
# Load Core Plugins
####################################################

I=0
PLUGINS=()

for PLUGINNAME in $(find "$COREPLUGINPATH" -maxdepth 1 -mindepth 1 -type d);
do
  FINDPATH=$COREPLUGINPATH/

  PLUGINNAME=${PLUGINNAME//$FINDPATH/}

	if [ -f "$COREPLUGINPATH/$PLUGINNAME/$PLUGINNAME" ]; then
		source "$COREPLUGINPATH/$PLUGINNAME/$PLUGINNAME"
		
		PLUGINS[$I]=$(echo $PLUGINNAME | tr /a-z/ /A-Z/)
	
		I=$I+1
		debug "Core Plugin \"$PLUGINNAME\" loaded."
	else 
		debug "\"$PLUGINNAME\" is not a valid plugin, Skipping.."
	fi
done

debug "Completed loading Core Plugins."

####################################################
# Load Plugins
####################################################

for PLUGINNAME in $(find "$PLUGINPATH" -maxdepth 1 -mindepth 1 -type d)
do
  FINDPATH=$PLUGINPATH/

  PLUGINNAME=${PLUGINNAME//$FINDPATH/}

	if [ -f "$PLUGINPATH/$PLUGINNAME/$PLUGINNAME" ]; then
		source "$PLUGINPATH/$PLUGINNAME/$PLUGINNAME"
		
		PLUGINS[$I]=$(echo $PLUGINNAME | tr /a-z/ /A-Z/)
	
		I=$I+1
		debug "Plugin \"$PLUGINNAME\" loaded."
	else 
		debug "\"$PLUGINNAME\" is not a valid plugin, Skipping.."
	fi
done

debug "Completed loading Plugins."