#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
UPDATE_PLUGIN_VERSION=1.1.0
UPDATE_PLUGIN_COMMAND="update self-update"
UPDATE_PLUGIN_FUNCTION="runUpdate"


function runUpdate {
	message "INFO" "Please run `eiger-update` to update eiger."
}
