#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
UPDATE_PLUGIN_COMMAND="update self-update"
UPDATE_PLUGIN_HELP_COMMAND="update"
UPDATE_PLUGIN_HELP_TEXT="Update Eiger to the latest stable version."
UPDATE_PLUGIN_FUNCTION="runUpdate"
UPDATE_PLUGIN_HELP="updateHelp"

UPDATE_PLUGIN_BRANCH="master"

function runUpdate {
  cd "$SCRIPTPATH"

	if ! [ -d "$SCRIPTPATH/.git" ]; then
		message "ERROR" "Missing git directory, please install eiger with the installer script. Exiting..."
		exit 1
	fi

	debug "Checking setup as repo complete"

  git fetch origin &> /dev/null

  if [ "$(git rev-parse origin/master)" != "$(git rev-parse HEAD)" ]; then
      message "INFO" "New version found, updating..."
      git pull origin master --force
      message "INFO" "Running new version..."
      exit 1
  fi

  message "INFO" "Already on the latest version."
}