#!/bin/bash

# Configs (Prefix with Plugin name)

# Plugin configs
NPM_PLUGIN_COMMAND="npm"
NPM_PLUGIN_ALLOW_ALIAS="true"
NPM_PLUGIN_HELP_COMMAND="npm"
NPM_PLUGIN_HELP_TEXT="npm is a package manager for the JavaScript programming language."
NPM_PLUGIN_FUNCTION="npmRun"
NPM_PLUGIN_HELP="npmHelp"
NPM_PLUGIN_INIT="npmInit"

NPM_PLUGIN_DOCKER_IMAGE="node"
NPM_PLUGIN_DOCKER_IMAGE_VERSION="latest"

# Default configs
NPM_ENABLED=true
NPM_PATH=/

# Run Node command inside docker container
function npmRun {

	if ! [ NPM_ENABLED ]; then
		message "ERROR" "NPM is disabled on this project."
	fi

	# Get docker image name
  local DOCKER_IMAGE=$(getDockerImageSetting "NPM")
  # Get docker image version
  local DOCKER_IMAGE_VERSION=$(getDockerImageVersionSetting "NPM")
  # Get plugin storage path
  local PLUGIN_STORAGE=$(getPluginStoragePath "npm")

  if [[ ! -z $PLUGIN_STORAGE/config/.npmrc ]]; then
	  mkdir -p $PLUGIN_STORAGE/config
	  echo "prefix=/npm-global" > $PLUGIN_STORAGE/config/.npmrc
	fi

  # Check for old version of setting version
  if [ ! -z $NPM_VERSION ]; then
    DOCKER_IMAGE_VERSION=$NPM_VERSION
  fi;

	$COMMAND_PREFIX docker run --rm -it -v "$PATH_PREFIX$PLUGIN_STORAGE/config/.npmrc":"/root/.npmrc" -v "$PATH_PREFIX$PLUGIN_STORAGE/storage":/npm-global -v "$PATH_PREFIX$(pwd)":/usr/src/app --workdir "$PATH_PREFIX/usr/src/app/$NPM_PATH" $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION $@
	debug "Finished running npm"
}

# Init - Eiger project config setup (Creates a .eiger config file for project)
function npmInit {

	local INIT_NPM_ENABLED=false
	local INIT_NPM_PATH=
	local INIT_NPM_IMAGE=
	local INIT_NPM_VERSION=
	
	if ask "Enabled NPM?" N; then
		INIT_NPM_ENABLED=true
		
		read -p "Relative path to package.json file? [/]): " UI_NPM_PATH
		INIT_NPM_PATH=${UI_NPM_PATH:-/}

		read -p "Which image would you like to use? [node]: " UI_NPM_IMAGE
		INIT_NPM_IMAGE=${UI_NPM_IMAGE:-node}
		
		read -p "Which version of the image would you like to use? [latest]: " UI_NPM_VERSION
		INIT_NPM_VERSION=${UI_NPM_VERSION:-latest}
	fi
	
	echo "NPM_ENABLED=$INIT_NPM_ENABLED
NPM_PATH=$INIT_NPM_PATH
NPM_DOCKER_IMAGE=$INIT_NPM_IMAGE
NPM_DOCKER_IMAGE_VERSION=$INIT_NPM_VERSION"
}